name: stacks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  injectable: ^2.3.2
  get_it: ^7.6.4
  equatable: ^2.0.5
  # Functional programming
  fpdart: ^1.1.0
  # BLoC State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  # Utils
  intl: ^0.19.0
  uuid: ^4.2.1
  # Form Validation
  formz: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7
  mockito: ^5.4.2
  bloc_test: ^9.1.5

flutter:
  uses-material-design: true
