name: stacks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  injectable: ^2.3.2
  get_it: ^7.6.4
  equatable: ^2.0.5
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_storage: ^11.6.0
  # Functional programming
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7
  mockito: ^5.4.2

flutter:
  uses-material-design: true
