// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMu7MZsAjkx1-8Ekz-_uDYYfXzSWuSVFA',
    appId: '1:692681414437:web:af5169f26b4dd124556ccc',
    messagingSenderId: '692681414437',
    projectId: 'stacks-restaurant-management',
    authDomain: 'stacks-restaurant-management.firebaseapp.com',
    storageBucket: 'stacks-restaurant-management.firebasestorage.app',
    measurementId: 'G-25KTPVTZSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3XEbVB4FYnLnF0bX6LIh2DtwOx7doDmk',
    appId: '1:692681414437:android:08780c7d8f8cf7d5556ccc',
    messagingSenderId: '692681414437',
    projectId: 'stacks-restaurant-management',
    storageBucket: 'stacks-restaurant-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxv52yKsdBK3SyDd1KhX3nhwRy06Tdg3M',
    appId: '1:692681414437:ios:8d2c510ff111a346556ccc',
    messagingSenderId: '692681414437',
    projectId: 'stacks-restaurant-management',
    storageBucket: 'stacks-restaurant-management.firebasestorage.app',
    iosClientId: '692681414437-m8hp50peeclb37sbbfj2ms4ffaq6itkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.stacks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxv52yKsdBK3SyDd1KhX3nhwRy06Tdg3M',
    appId: '1:692681414437:ios:8d2c510ff111a346556ccc',
    messagingSenderId: '692681414437',
    projectId: 'stacks-restaurant-management',
    storageBucket: 'stacks-restaurant-management.firebasestorage.app',
    iosClientId: '692681414437-m8hp50peeclb37sbbfj2ms4ffaq6itkm.apps.googleusercontent.com',
    iosBundleId: 'com.example.stacks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMu7MZsAjkx1-8Ekz-_uDYYfXzSWuSVFA',
    appId: '1:692681414437:web:26d36c3dee7bc787556ccc',
    messagingSenderId: '692681414437',
    projectId: 'stacks-restaurant-management',
    authDomain: 'stacks-restaurant-management.firebaseapp.com',
    storageBucket: 'stacks-restaurant-management.firebasestorage.app',
    measurementId: 'G-9FB6MYCQVW',
  );

}